context:
  version: "19.0.4"

package:
  name: release-it
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-it/-/release-it-${{ version }}.tgz
  sha256: a93098b6d129bcd3e2fa187b66c318a5a198b1c442029da5dd10c0c4fa302458

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-it --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Automate versioning and package publishing
  homepage: https://github.com/release-it/release-it
  repository: https://github.com/release-it/release-it

extra:
  recipe-maintainers:
    - danielnachun
