context:
  version: "19.2.4"

package:
  name: release-it
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-it/-/release-it-${{ version }}.tgz
  sha256: 56c91ae9295a790fab1b96beeb823855cb6eb3e52c70bce1ec0befd22db2ea7a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-it --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Automate versioning and package publishing
  homepage: https://github.com/release-it/release-it
  repository: https://github.com/release-it/release-it

extra:
  recipe-maintainers:
    - danielnachun
