context:
  version: "20.0.0"

package:
  name: release-it
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-it/-/release-it-${{ version }}.tgz
  sha256: e65b924717e8020b417aaee5b4fd85cc354f6a6e8224410bfaa78dad6e52c6f8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-it --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Automate versioning and package publishing
  homepage: https://github.com/release-it/release-it
  repository: https://github.com/release-it/release-it

extra:
  recipe-maintainers:
    - danielnachun
