context:
  version: "21.0.0"

package:
  name: release-it
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-it/-/release-it-${{ version }}.tgz
  sha256: 1b307afe130be6b4e4db1c4aa5988764726f8640d6a40e1e28ac74189c27647e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-it --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Automate versioning and package publishing
  homepage: https://github.com/release-it/release-it
  repository: https://github.com/release-it/release-it

extra:
  recipe-maintainers:
    - danielnachun
