context:
  version: "20.2.0"

package:
  name: release-it
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/release-it/-/release-it-${{ version }}.tgz
  sha256: 2768b4253d0d83d9fc02e5ecd7f2c60620575800be03954ecd4ec0545aecb25c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - release-it --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Automate versioning and package publishing
  homepage: https://github.com/release-it/release-it
  repository: https://github.com/release-it/release-it

extra:
  recipe-maintainers:
    - danielnachun
